services:
  zonos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zonos_container
    networks: 
      - dokploy-network
    runtime: nvidia
    stdin_open: true
    tty: true
    command: ["python3", "gradio_interface.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - GRADIO_SHARE=False
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zonos.rule=Host(`zonos.archive.neurolearninglabs.com`)"
      - "traefik.http.routers.zonos.entrypoints=websecure"
      - "traefik.http.routers.zonos.tls.certresolver=cloudflare"
      - "traefik.http.services.zonos.loadbalancer.server.port=7860"
networks:
  dokploy-network:
    external: true
